### ISSUE TITLE
Küsimustiku algatamine

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uldpadevused#2]
Küsimustiku algatamiseks valib kasutaja nimekirjast sobiva küsimustiku. Seejärel määrab kasutaja küsimustikule aktiivse oleku aja (tundides-minutites) ning algusaja (kuupäev, kellaaeg).

Küsimustikuga liitumiseks on vajalik kood, mis genereeritakse küsimustiku algatamise hetkel. Kood on 6-kohaline numbrite jada, mis kehtib eelnevalt määratud aja.

![screenshot 2018-09-27 at 11 42 21](https://user-images.githubusercontent.com/380007/46133955-70c30e80-c24a-11e8-8671-35bc5450c372.png)

**Comment by leoste** [comment]
Algusaeg võiks lisaks kuupäevale sisaldada ka kellaaega.

**Comment by leoste** [comment]
disain pole veel päris see
