### ISSUE TITLE
Tulemuste sirvimine

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uldpadevused#6]
Tulemuste lehel kuvatakse tabel kõigi lõppenud ja algavate küsimustikega. Tulemusi on võimalik sorteerida kuupäeva ja staatuse järgi. Küsimustiku nime taga olev link kuvab kasutajale kasutatava küsimustiku.

![screenshot 2018-09-27 at 11 07 50](https://user-images.githubusercontent.com/380007/46132027-bdf0b180-c245-11e8-9a95-64d59e56216c.png)

**Comment by leoste** [comment]
<img width="719" alt="screenshot 2018-10-15 at 11 07 07" src="https://user-images.githubusercontent.com/35530198/46937657-89b12980-d06a-11e8-895f-238f390812cf.png">
