### ISSUE TITLE
aja peale küsimustiku ette tiitel et "nüüd hakkab pihta"

### ISSUE THREAD

**Issue by leoste** [centre-for-educational-technology/Uldpadevused#66]

**Comment by tammets** [comment]
![screenshot 2018-12-14 at 14 13 08](https://user-images.githubusercontent.com/380007/50002916-6f33f780-ffaa-11e8-97ab-3bc140eb16c9.png)

**Comment by leoste** [comment]
Tegelt ikkagi las ta olla lol
