### ISSUE TITLE
Küsimustik - Lugmot-laused-4kl

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uldpadevused#7]
![2](https://user-images.githubusercontent.com/380007/46133498-58062900-c249-11e8-8a83-93d67ca50789.png)

**Comment by tammets** [comment]
Vastamiseks on aega 60 sekundit (+5 sekundit).

**Comment by tammets** [comment]
lausete lugemine / alumine osa. mot eest ära, näod (fail)

**Comment by leoste** [comment]
järgmine/eelmine nupp ära võtta, järgmisele lehele läheb kohe kui küsimusele vastad
