### ISSUE TITLE
Küsimustik - lugemise metakognitsioon lastele

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uldpadevused#8]
![yldpadevused3](https://user-images.githubusercontent.com/380007/46135137-2ee79780-c24d-11e8-974c-9f72a62f4031.png)

**Comment by tammets** [comment]
Ei ole ajalimiiti.

**Comment by leoste** [comment]
ca1b9a24c951eb658509b7169518638cf5102b4d
